0.3.0 - Update echarts, echarts-for-react and eslint dependencies
nginformatica/amazing-react-charts pull request #5
Opened 2020-11-16 20:06 UTC by leorigon

## Updates:
 - echarts to last stable version;
 - echarts-for-react to last stable version;
 - eslint and his configs to improve the code style;

## Improves:
 - remove all the type casts;
 - remove all the nested ternaries; 
 - use the default types from echarts;
 - remove unecessary functions and improve code with the new linter configs;

2020-11-16 20:19 UTC, merged

2020-11-16 20:24 UTC, jeovazero requested changes

2020-11-16 20:24 UTC, jeovazero commented on src/core/AudiometryChart.tsx
> +    items[0].data.value || items[0].data.value === 0
se o `items` for vazio vai dar runtime error

2020-11-16 20:24 UTC, jeovazero commented on src/core/DonutChart.tsx
> +      show: titleProps !== undefined,
nao pode ser um `!!titleProps` ?

2020-11-16 20:24 UTC, jeovazero commented on src/core/DonutChart.tsx
> +            totalValues.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.'),
acho melhor voce criar uma func com isso `totalValues.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.')` e colocar um exemplo de entrada e saida, apenas para documentação, para ter uma ideia do que a regex faz

2020-11-16 20:24 UTC, jeovazero commented on src/core/PieChart.tsx
> +    const percent = value !== 0 ? (value * (100 / totalValues)).toFixed(2) : 0
essa expressao do percent ta repetida em outro componente, acho melhor criar uma função pra isso

2020-11-16 20:24 UTC, jeovazero commented on src/core/PieChart.tsx
> +      show: titleProps !== undefined,
aqui tambem caberia a sugestao do `!!titleProps`

2020-11-16 20:24 UTC, jeovazero commented on src/core/auxiliarFunctions.ts
> +  const percent = value !== 0 ? (value * (100 / valueTotal)).toFixed(2) : 0
segue a mesma recomendação de criar uma função pra isso

2020-11-17 13:57 UTC, jacksjm commented on src/core/auxiliarFunctions.ts
> +  const percent = value !== 0 ? (value * (100 / valueTotal)).toFixed(2) : 0
isso vai dar tipos diferentes, não  (string | number)